# Generated by Django 5.0.1 on 2024-03-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Имя продукта')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('price_medium', models.IntegerField(default=0, verbose_name='Цена для медиум')),
                ('price_small', models.IntegerField(default=0, verbose_name='Цена для маленькой')),
                ('briefly', models.CharField(max_length=100, verbose_name='Коротко о еде')),
                ('image', models.ImageField(upload_to='menu/')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(verbose_name='Все о еде')),
                ('discount', models.IntegerField(blank=True, default=0, verbose_name='Скидки')),
                ('discount_main', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Блюдо',
            },
        ),
    ]
