# Generated by Django 5.0.1 on 2024-03-13 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_category_food_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
    ]
