# Generated by Django 5.0.3 on 2024-04-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='avatar',
            field=models.ImageField(default='user.png', upload_to='profile_image/'),
        ),
    ]
